// Build the dashboard's data files from the raw scans.
//   xhs_authors.json  → dashboard/data.js   (creators to follow, with avatars)
//   me.json           → dashboard/me.js     (your notes, categorized + analyzed)
//
// Both outputs load via <script>, so the dashboard works opened straight from
// disk (file:// blocks fetch). Both are gitignored — tooling is public, your
// data is local.
//
// Categorization + analysis live HERE, not in the puller: pure transform, safe
// to re-run and tweak without spending API calls.
//
// Usage: node scripts/build_dashboard.mjs [--lang en|zh]
//   --lang sets the dashboard's default UI language (the UI also has a live toggle).
//   Category LABELS are bilingual; category KEYWORDS stay Chinese (they match Chinese posts).

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const langArg = (process.argv.find(a => a.startsWith('--lang')) || '').split('=')[1]
  || (process.argv[process.argv.indexOf('--lang') + 1] === 'en' ? 'en' : null);
const LANG = langArg === 'en' ? 'en' : 'zh';
const read = f => JSON.parse(fs.readFileSync(path.join(root, f), 'utf8'));
const write = (f, obj) => {
  fs.mkdirSync(path.join(root, 'dashboard'), { recursive: true });
  fs.writeFileSync(path.join(root, 'dashboard', f),
    `// Generated by scripts/build_dashboard.mjs — do not edit, gitignored.\nwindow.CM_LANG = ${JSON.stringify(LANG)};\nwindow.${f === 'me.js' ? 'ME' : 'SCAN'} = ${JSON.stringify(obj)};\n`);
};

// ── categories ──────────────────────────────────────────────────────────
// Keyword rules over title+desc. First rule with the most hits wins; ties go
// to rule order. Tune the keyword rules to the account's actual corpus.
const CATS = [
  { key: 'ai-tools',    label: 'AI 工具 / 工作流', en: 'AI Tools / Workflows', emoji: '🛠️',
    kw: ['skills','claude code','claude skills','vibe cod','vibe code','cursor','codex','prompt','工作流','工具','app','substack','知识库','automation','mcp','飞书','n8n'] },
  { key: 'ai-research',  label: 'AI 研究 / 学术', en: 'AI Research', emoji: '🔬',
    kw: ['research','paper','neurips','ppo','llm','agent','karpathy','anthropic','reasoning','推理','神经','encoder','fine-tun','rl','model','arxiv','yejin','david bau','姚顺雨','engineering新书','ai engineering','moe','记忆','memory','evals','eval','经验时代','builders该'] },
  { key: 'career',       label: '职场 / 求职', en: 'Career / Job Search', emoji: '💼',
    kw: ['求职','简历','面试','大厂','工程师','offer','找工作','职场','邪修','跳槽','秋招','实习','career','interview','gtm','造势','build a cult','一人公司','沟通','leader','high performing','ic','wes kao','dan koe','沟通','带着逻辑'] },
  { key: 'product',      label: '产品 / 增长', en: 'Product / Growth', emoji: '📈',
    kw: ['冷启动','早期用户','增长','product','增长黑客','pmf','用户体验','ux','设计ai','设计 ai','go-to-market','定位','positioning'] },
  { key: 'creators',     label: '创始人 / taste', en: 'Founders / Taste', emoji: '👤',
    kw: ['创始人','taste','founder','delphi','sublime','有taste','be more human'] },
  { key: 'networking',   label: '社交 / 连接', en: 'Networking', emoji: '☕',
    kw: ['coffee chat','coffee','约','出差','links','认领','聊','meetup','networking','head of gtm'] },
  { key: 'fashion',      label: '时尚 / 穿搭', en: 'Fashion / OOTD', emoji: '👗',
    kw: ['穿搭','西装','裙','丝巾','包臀','大衣','港风','露背','芭比','high跟','高跟','valentino','helmut lang','alexander wang','alexa chung','toga','i am gia','ellery','haider','ackermann','薄纱','棉花糖','种草','好物','仙女','盛装','fashion','ootd','gia'] },
  { key: 'life-travel',  label: '生活 / 旅行', en: 'Life / Travel', emoji: '🌊',
    kw: ['vlog','la jolla','san diego','圣地亚哥','夏威夷','oregon','墨西哥','日落','日出','浮潜','zoo','河马','徒步','sedona','生日','birthday','周末','weekend','欧胡','captain','喜茶','低卡','吃喝','压马路','上海','毕业','ucla','宾大','申请','q&a','面朝大海','captain bruce','亡灵节'] },
  { key: 'growth-self',  label: '自我成长 / 心智', en: 'Growth / Mindset', emoji: '🌱',
    kw: ['self-care','self care','反刍','读书','内心','运动员','能量','钟形罩','思维训练','冥想','焦虑','人生','思考','comm |','30s','mood diary','精力','multi-task','好问题','问出好'] },
  { key: 'recommend',    label: '推荐 / 播客', en: 'Recommends / Podcasts', emoji: '🎙️',
    kw: ['lenny','podcast','播客','采访','all-in','推荐','访谈','notion','aha moment','年度回顾','grok','视频生成'] },
];

function categorize(text) {
  const t = text.toLowerCase();
  let best = null, bestN = 0;
  for (const c of CATS) {
    const n = c.kw.reduce((s, k) => s + (t.includes(k) ? 1 : 0), 0);
    if (n > bestN) { bestN = n; best = c; }
  }
  return best ? best.key : 'other';
}

const median = arr => {
  if (!arr.length) return 0;
  const s = [...arr].sort((a, b) => a - b);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};

// analysis files are optional — fold them in when present
const readIf = f => fs.existsSync(path.join(root, f)) ? read(f) : null;
const creatorAnalyses = {};
const caDir = path.join(root, 'analysis', 'creators');
if (fs.existsSync(caDir)) {
  for (const f of fs.readdirSync(caDir)) {
    const m = f.match(/^(.+)-analysis\.json$/);
    if (m) { try { creatorAnalyses[m[1]] = JSON.parse(fs.readFileSync(path.join(caDir, f), 'utf8')); } catch {} }
  }
}
// pulled per-creator notes (top of each, for the detail view)
const creatorNotes = {};
const cnDir = path.join(root, 'creators');
if (fs.existsSync(cnDir)) {
  for (const f of fs.readdirSync(cnDir)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(cnDir, f), 'utf8'));
      creatorNotes[f.replace('.json', '')] = (c.notes || []).slice(0, 30).map(n => ({
        title: n.title, likes: n.likes, saves: n.saves, comments: n.comments,
        shares: n.shares, type: n.type, url: n.url,
      }));
    } catch {}
  }
}

// ── X + Substack creators (with analysis) ────────────────────────────────
function loadPlatform(dir, anaDir, keyField) {
  const out = [];
  const d = path.join(root, dir);
  if (!fs.existsSync(d)) return out;
  for (const f of fs.readdirSync(d)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(d, f), 'utf8'));
      const key = c[keyField];
      const ana = path.join(root, anaDir, `${key}-analysis.json`);
      c.analysis = fs.existsSync(ana) ? JSON.parse(fs.readFileSync(ana, 'utf8')) : null;
      out.push(c);
    } catch {}
  }
  return out;
}
const xCreators = loadPlatform('creators_x', 'analysis/x', 'handle')
  .map(c => ({ handle: c.handle, name: c.name, desc: c.desc, avatar: c.avatar,
    followers: c.followers, analysis: c.analysis,
    posts: (c.tweets || []).slice(0, 10).map(t => ({ text: t.text, likes: t.likes,
      retweets: t.retweets, bookmarks: t.bookmarks, replies: t.replies, views: t.views, url: t.url })) }))
  .sort((a, b) => b.followers - a.followers);
const subCreators = loadPlatform('creators_sub', 'analysis/sub', 'slug')
  .map(c => ({ slug: c.slug, name: c.name, desc: c.desc, avatar: c.avatar, feed: c.feed,
    analysis: c.analysis, posts: (c.posts || []).slice(0, 10) }));

// ── creators → data.js ──────────────────────────────────────────────────
if (fs.existsSync(path.join(root, 'xhs_authors.json'))) {
  const raw = read('xhs_authors.json');
  const creators = raw.map(a => ({
    name: a.name, id: a.id, avatar: a.avatar || '',
    kws: a.kws, eng: a.eng, col: a.col, hits: a.hits, titles: a.titles || [],
    analysis: creatorAnalyses[a.id] || null,
    posts: creatorNotes[a.id] || null,
  }));
  const keywords = [...new Set(creators.flatMap(c => c.kws))].sort();
  write('data.js', {
    landscape: readIf('analysis/landscape.json'),
    xLandscape: readIf('analysis/x-landscape.json'),
    subLandscape: readIf('analysis/sub-landscape.json'),
    x: xCreators,
    sub: subCreators,
    vault: (() => {
      const v = readIf('vault/vault.json');
      const q = readIf('vault/interview-questions.json');
      // Questions are keyed by the idea's stable `id`; numeric keys are a legacy
      // fallback (fragile — breaks if ideas are ever inserted or deleted).
      if (v && q) v.ideas.forEach((idea, i) => {
        idea.questions = (idea.id && q[idea.id]) || q[String(i)] || [];
      });
      return v;
    })(),
    meta: {
      creators: creators.length,
      notes: creators.reduce((s, c) => s + c.hits, 0),
      keywords: keywords.length,
      likes: creators.reduce((s, c) => s + c.eng, 0),
      saves: creators.reduce((s, c) => s + c.col, 0),
      costUsd: +(keywords.length * 0.001).toFixed(3),
    },
    keywords, creators,
  });
  console.log(`data.js  → ${creators.length} creators (${creators.filter(c => c.avatar).length} with avatars)`);
}

// ── my notes → me.js ────────────────────────────────────────────────────
if (fs.existsSync(path.join(root, 'me.json'))) {
  const { profile, notes } = read('me.json');

  const engAll = notes.map(n => n.likes + n.saves + n.comments + n.shares);
  const medEng = median(engAll);
  const medSaveRate = median(notes.filter(n => n.likes).map(n => n.saves / n.likes));

  const enriched = notes.map(n => {
    const eng = n.likes + n.saves + n.comments + n.shares;
    return {
      ...n,
      cat: categorize(`${n.title} ${n.desc}`),
      eng,
      saveRate: n.likes ? +(n.saves / n.likes).toFixed(2) : 0,
      shareRate: n.likes ? +(n.shares / n.likes).toFixed(3) : 0,
      // outlier vs your own median — this is what /bootstrap-voice should learn from
      outlier: medEng > 0 && eng >= medEng * 3,
    };
  }).sort((a, b) => b.eng - a.eng);

  // per-category rollup
  const byCat = {};
  for (const c of [...CATS, { key: 'other', label: '其他', en: 'Other', emoji: '•' }]) {
    const items = enriched.filter(n => n.cat === c.key);
    if (!items.length) continue;
    byCat[c.key] = {
      label: c.label, en: c.en, emoji: c.emoji, count: items.length,
      likes: items.reduce((s, n) => s + n.likes, 0),
      saves: items.reduce((s, n) => s + n.saves, 0),
      medEng: median(items.map(n => n.eng)),
      top: items[0]?.title || '',
    };
  }

  // monthly time-series (activity is concentrated in the last ~18 months)
  const monthMap = {};
  for (const n of notes) {
    if (!n.created) continue;
    const d = new Date(n.created);
    const k = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    (monthMap[k] ||= []).push(n);
  }
  const months = Object.keys(monthMap).sort();
  // fill gaps between first and last so the axis is continuous
  const series = [];
  if (months.length) {
    let [y, m] = months[0].split('-').map(Number);
    const [ly, lm] = months[months.length - 1].split('-').map(Number);
    while (y < ly || (y === ly && m <= lm)) {
      const k = `${y}-${String(m).padStart(2, '0')}`;
      const items = monthMap[k] || [];
      const engs = items.map(n => n.likes + n.saves + n.comments + n.shares);
      series.push({
        month: k, count: items.length,
        likes: items.reduce((s, n) => s + n.likes, 0),
        saves: items.reduce((s, n) => s + n.saves, 0),
        comments: items.reduce((s, n) => s + n.comments, 0),
        shares: items.reduce((s, n) => s + n.shares, 0),
        medEng: median(engs),
      });
      m++; if (m > 12) { m = 1; y++; }
    }
  }

  write('me.js', {
    profile,
    analysis: readIf('analysis/me-analysis.json'),
    voice: readIf('voice/voice.json'),
    draft: readIf('drafts/current.json'),
    series,
    stats: {
      notes: notes.length,
      videos: notes.filter(n => n.type === 'video').length,
      medEng, medSaveRate: +medSaveRate.toFixed(2),
      totalLikes: notes.reduce((s, n) => s + n.likes, 0),
      totalSaves: notes.reduce((s, n) => s + n.saves, 0),
      totalShares: notes.reduce((s, n) => s + n.shares, 0),
    },
    cats: CATS.map(c => ({ key: c.key, label: c.label, en: c.en, emoji: c.emoji })),
    byCat,
    notes: enriched,
  });
  console.log(`me.js    → ${profile.name}: ${notes.length} notes, ${Object.keys(byCat).length} categories, median engagement ${medEng}`);
  console.log('           categories:', Object.entries(byCat).map(([k, v]) => `${v.emoji}${v.count}`).join(' '));
}
